### ISSUE TITLE
running `chromatic example ./test` produces error

### ISSUE THREAD

**Issue by sturobson** [arnog/chromatic#1]
Following the commands from the README - 

`npm install -g @arnog/chromatic`

I get an error when trying to "create a directory with an example", running - 

`chromatic example ./test`

This gave me the following error:

```
⚠️   Format not specified. Using "yaml". Use --format to indicate which output format to use.

✘   File not found: example
```

I'll persevere for a bit, and if I find a solution I'll update accordingly :) <3

**Comment by arnog** [comment]
Congratulations and thank you for reporting the first issue for Chromatic.
This happened because the npm repository was out of date with the GitHub repo which included this feature. I've pushed a new version to npm now. If you update, it should work.
